# Generated by Django 5.2.2 on 2025-07-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
